# Generated by Django 3.2.8 on 2022-01-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_client_hourly_rate_currency'),
        ('prepaid', '0009_alter_prepaid_end_of_subscription'),
        ('post_paid', '0030_accountbalance_billing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidInteractionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_prepaid_interaction_rates', to='authentication.client')),
                ('prepaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_interaction_rates', to='prepaid.customerinteractionprepaid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostpaidInteractionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_post_paid_interaction_rates', to='authentication.client')),
                ('post_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_paid_interaction_rates', to='post_paid.customerinteractionpostpaid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
