# Generated by Django 3.2.7 on 2021-11-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_client_hourly_rate_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forwarding_number', models.CharField(help_text="Customer's phone line", max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_forwarding_informations', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VodaconnectSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_description', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipTrunkLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zip_trunk_details', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('forwarding_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarding_information_zip_trunk_logins', to='vodaconnect.forwardinginformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoipInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vodaconnect_number', models.CharField(max_length=250)),
                ('client_code', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_voip_information', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TotalNumberOfExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension_number', models.CharField(max_length=250)),
                ('extension_logins', models.CharField(max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('forwarding_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarding_information_total_number_of_extensions', to='vodaconnect.forwardinginformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_in_production', models.CharField(choices=[('new_prospect', 'New Prospect'), ('new_request', 'New Request'), ('pending_request', 'Pending Request'), ('call_email_follow_up', 'Call/Email follow up'), ('ready_to_start', 'Ready to Start'), ('sign_up_ready_for_setup', 'Sign up - Ready for Setup'), ('active_live_in_production', 'Active - Live in Production'), ('request_for_cancellation', 'Request for Cancellation'), ('email_sent_for_cancellation', 'Email sent for cancellation'), ('account_cancelled_by_vodaconnect', 'Account cancelled by Vodaconnect'), ('recurring_charge_cancelled', 'Recurring charge Cancelled'), ('account_cancelled', 'Account Cancelled')], max_length=250)),
                ('type_of_request', models.CharField(choices=[('new_number_request', 'New number request'), ('porting_request', 'Porting request'), ('other_request', 'Other request')], max_length=250)),
                ('testimony', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_subscriber_statuses', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanSummaryAndPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_year', models.CharField(max_length=100)),
                ('plan_type', models.CharField(max_length=250)),
                ('total_minutes', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cost_of_plan', models.DecimalField(decimal_places=2, max_digits=19)),
                ('payment_reference', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('date_of_paid', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_plan_summary_and_payments', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('recurring_bill', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], max_length=100)),
                ('paypal_details_for_billing', models.TextField()),
                ('due_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_plan_detail', to='authentication.client')),
                ('plan_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_detail_plan_types', to='vodaconnect.plantype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('forwarding_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarding_information_other_logins', to='vodaconnect.forwardinginformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivePlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_minutes_included', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True)),
                ('cost_of_plan', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True)),
                ('start_of_plan', models.DateField()),
                ('end_of_plan', models.DateField()),
                ('account_status', models.BooleanField(default=True)),
                ('recurring_bill', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_vodaconnect_active_plan_details', to='authentication.client')),
                ('plan_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_plan_detail_plan_types', to='vodaconnect.plantype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_request_date', models.DateField()),
                ('request_date_initiated', models.DateField()),
                ('date_line_activated', models.DateField()),
                ('date_line_terminated', models.DateField()),
                ('phone_line_status', models.CharField(blank=True, choices=[('inactive', 'Inactive'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], max_length=30)),
                ('client_company_user_category', models.CharField(choices=[('callme_com_ph', 'CALLME.COM.PH'), ('psalmsglobal', 'PSALMSGLOBAL'), ('landmaster', 'LANDMASTER'), ('vodaconnect', 'VODACONNECT')], max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_activation_detail', to='authentication.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
