# Generated by Django 3.2.9 on 2021-11-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_client_hourly_rate_currency'),
        ('vodaconnect', '0002_othercharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='vodaconnectsignup',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_vodaconnect_sign_up', to='authentication.client'),
        ),
    ]
