# Generated by Django 3.2.8 on 2021-11-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaconnect', '0003_vodaconnectsignup_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationdetail',
            name='date_line_terminated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalnumberofextension',
            name='extension_logins',
            field=models.TextField(blank=True),
        ),
    ]
