# Generated by Django 3.2.8 on 2021-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaconnect', '0004_auto_20211125_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansummaryandpayment',
            name='date_of_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
