# Generated by Django 3.2.8 on 2021-12-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vodaconnect', '0006_alter_othercharge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeplandetail',
            name='end_of_plan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
