# Generated by Django 3.2.8 on 2023-06-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
