# Generated by Django 3.2.7 on 2021-09-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_client_hourly_rate_currency'),
        ('post_paid', '0029_auto_20210831_1011'),
        ('prepaid', '0003_auto_20210611_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customerinteractionprepaid',
            options={'ordering': ['-ticket_number'], 'verbose_name': 'Prepaid Customer Interaction board', 'verbose_name_plural': 'Prepaid Customer Interactions board'},
        ),
        migrations.RenameField(
            model_name='prepaidsubscription',
            old_name='amount',
            new_name='monthly_fee',
        ),
        migrations.RenameField(
            model_name='prepaidsubscription',
            old_name='amount_currency',
            new_name='monthly_fee_currency',
        ),
        migrations.RemoveField(
            model_name='minutesreport',
            name='monthly_usage',
        ),
        migrations.RemoveField(
            model_name='prepaidsubscription',
            name='monthly_subscription',
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='account_total_spending',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='total_spending',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='customerinteractionprepaid',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerinteractionprepaid',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepaid_customer_interaction_agents', to='authentication.staff'),
        ),
        migrations.AddField(
            model_name='customerinteractionprepaid',
            name='county',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customerinteractionprepaid',
            name='internal_auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepaid_customer_interaction_auditors', to='post_paid.internalauditor'),
        ),
        migrations.AddField(
            model_name='customerinteractionprepaid',
            name='reference_number',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customerinteractionprepaid',
            name='state',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='minutesreport',
            name='consumed_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='minutesreport',
            name='customer_interaction_mins_overview',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='minutesreport',
            name='general_request_mins_overview',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='paymentsummary',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='paymentsummary',
            name='payment_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prepaidsubscription',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerinteractionprepaid',
            name='general_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_customer_interaction_general_calls', to='post_paid.generalcall'),
        ),
        migrations.AlterField(
            model_name='customerinteractionprepaid',
            name='interested_to_buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_interested_to_buy_interactions', to='post_paid.interestedtobuy'),
        ),
        migrations.AlterField(
            model_name='customerinteractionprepaid',
            name='interested_to_sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_interested_to_sell_interactions', to='post_paid.interestedtosell'),
        ),
        migrations.AddField(
            model_name='prepaidsubscription',
            name='plan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepaid_plan_types', to='prepaid.plantype'),
        ),
    ]
