# Generated by Django 3.2.7 on 2021-09-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_client_hourly_rate_currency'),
        ('prepaid', '0006_jobordercommentprepaid_joborderprepaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_called', models.DateField(auto_now_add=True)),
                ('ticket_number', models.CharField(blank=True, max_length=250)),
                ('total_minutes', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('approved', 'Approved')], default='approved', max_length=50)),
                ('client_feedback_status', models.CharField(blank=True, choices=[('dispute', 'Dispute'), ('n/a', 'N/A'), ('clarification', 'Clarification'), ('case_closed', 'Case Closed'), ('dispute_on_progress', 'Dispute on progress'), ('resolution_given', 'Resolution given'), ('other', 'Other')], default='n/a', max_length=100)),
                ('dispute_details', models.TextField(blank=True)),
                ('other_feedback', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('internal_management_ticket_status', models.CharField(blank=True, choices=[('na', 'N/A'), ('case_closed', 'Case Closed'), ('dispute_on_progress', 'Dispute on progress'), ('resolution_given', 'Resolution given'), ('others', 'Others')], default='na', max_length=100)),
                ('memo_solution_from_the_mgmt', models.TextField(blank=True)),
                ('other_ticket_status', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepaid_agent_interaction_records', to='authentication.staff')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepaid_client_interaction_records', to='authentication.client')),
                ('customer_interaction_prepaid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_interaction_prepaid_records', to='prepaid.customerinteractionprepaid')),
            ],
            options={
                'verbose_name': 'Call Record Breakdown',
                'verbose_name_plural': 'Call Record Breakdown',
                'ordering': ['-client'],
            },
        ),
    ]
