# Generated by Django 3.2.9 on 2021-11-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepaid', '0008_alter_prepaidsubscription_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaid',
            name='end_of_subscription',
            field=models.DateField(blank=True, null=True),
        ),
    ]
