# Generated by Django 3.2.3 on 2021-05-31 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_user_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callme', '0002_remove_phonesystem_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInteractionPostPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(blank=True, max_length=250)),
                ('apn', models.CharField(max_length=250)),
                ('caller_full_name', models.CharField(max_length=250)),
                ('caller_phone', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('reason_of_the_call', models.TextField(blank=True)),
                ('total_minutes', models.IntegerField(blank=True, default=0)),
                ('crm', models.CharField(choices=[('yes', 'yes'), ('no', 'No'), ('needs_validation', 'Needs validation'), ('invalid_data', 'Invalid data'), ('needs_follow_up', 'Needs follow-up')], max_length=250)),
                ('leads_transferred_crm', models.CharField(choices=[('needs_transferred', 'Needs transferred'), ('transfer_complete', 'Transfer complete'), ('na', 'N/A')], max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='callme.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterestedToBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterestedToSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='PostPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_minutes', models.CharField(max_length=250)),
                ('start_of_plan', models.CharField(max_length=250)),
                ('end_of_plan', models.CharField(max_length=250)),
                ('account_status', models.BooleanField()),
                ('recurring_bill', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.client')),
                ('cost_of_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post_paid.costplan')),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post_paid.plantype')),
            ],
            options={
                'ordering': ['-client'],
            },
        ),
        migrations.CreateModel(
            name='InteractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_called', models.DateField(auto_now_add=True)),
                ('total_minutes', models.IntegerField()),
                ('summary', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.staff')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.client')),
            ],
            options={
                'ordering': ['-client'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInteractionPostPaidComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('customer_interaction_post_paid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post_paid.customerinteractionpostpaid')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customerinteractionpostpaid',
            name='general_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_paid.generalcall'),
        ),
        migrations.AddField(
            model_name='customerinteractionpostpaid',
            name='interested_to_buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_paid.interestedtobuy'),
        ),
        migrations.AddField(
            model_name='customerinteractionpostpaid',
            name='interested_to_sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_paid.interestedtosell'),
        ),
    ]
