# Generated by Django 3.2.4 on 2021-06-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_client_hourly_rate_currency'),
        ('post_paid', '0004_interactionrecord_customer_interaction_post_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinteractionpostpaid',
            name='total_minutes',
        ),
        migrations.AlterField(
            model_name='interactionrecord',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_paid_agent_interaction_records', to='authentication.staff'),
        ),
        migrations.AlterField(
            model_name='interactionrecord',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_paid_client_interaction_records', to='authentication.client'),
        ),
    ]
