# Generated by Django 3.2.4 on 2021-06-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0006_customerinteractionpostpaid_script_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteractionpostpaid',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerinteractionpostpaid',
            name='county',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customerinteractionpostpaid',
            name='reference_number',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customerinteractionpostpaid',
            name='state',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
