# Generated by Django 3.2.4 on 2021-07-07 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0008_joborderpostpaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderpostpaid',
            name='caller_interaction_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interaction_job_orders', to='post_paid.customerinteractionpostpaid'),
        ),
    ]
