# Generated by Django 3.2.4 on 2021-07-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0010_jobordercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('approved', 'Approved')], default='approved', max_length=50),
        ),
    ]
