# Generated by Django 3.2.5 on 2021-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0011_interactionrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutesreport',
            name='plan_allocated_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
