# Generated by Django 3.2.5 on 2021-07-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0012_minutesreport_plan_allocated_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'ordering': ['-client'], 'verbose_name': 'Account Balance', 'verbose_name_plural': 'Account Balance'},
        ),
        migrations.AlterModelOptions(
            name='accountcharge',
            options={'verbose_name': 'Account Charge', 'verbose_name_plural': 'Account Charge'},
        ),
        migrations.AlterModelOptions(
            name='costplan',
            options={'ordering': ['-name'], 'verbose_name': 'Cost of Plan', 'verbose_name_plural': 'Cost of Plans'},
        ),
        migrations.AlterModelOptions(
            name='customerinteractionpostpaid',
            options={'verbose_name': 'Postpaid Customer Interaction Board', 'verbose_name_plural': 'Postpaid Customer Interaction Board'},
        ),
        migrations.AlterModelOptions(
            name='interactionrecord',
            options={'ordering': ['-client'], 'verbose_name': 'Call Record Breakdown', 'verbose_name_plural': 'Call Record Breakdown'},
        ),
        migrations.AlterModelOptions(
            name='joborderpostpaid',
            options={'ordering': ['-ticket_number'], 'verbose_name': 'List of Job Order', 'verbose_name_plural': 'List of Job Orders'},
        ),
        migrations.AlterModelOptions(
            name='minutesreport',
            options={'verbose_name': 'summary of Minute', 'verbose_name_plural': 'summary of Minutes'},
        ),
        migrations.AlterModelOptions(
            name='monthlycharge',
            options={'ordering': ['-client'], 'verbose_name': 'Plan Summary and Payment'},
        ),
        migrations.AlterModelOptions(
            name='plantype',
            options={'ordering': ['-name'], 'verbose_name': 'Plan Type Category', 'verbose_name_plural': 'Plan Type Category'},
        ),
        migrations.AlterModelOptions(
            name='postpaid',
            options={'ordering': ['-client'], 'verbose_name': 'Active Plan Detail', 'verbose_name_plural': 'Active Plan Details'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-company'], 'verbose_name': 'Plan Subscription Info', 'verbose_name_plural': 'Plan Subscription Info'},
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='cost_of_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='end_of_plan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postpaid',
            name='start_of_plan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
