# Generated by Django 3.2.5 on 2021-08-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0013_auto_20210729_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalcall',
            options={'verbose_name': 'Type of Caller'},
        ),
    ]
