# Generated by Django 3.2.5 on 2021-08-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0014_alter_generalcall_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionrecord',
            name='client_feedback_status',
            field=models.CharField(blank=True, choices=[('dispute', 'Dispute'), ('n/a', 'N/A'), ('clarification', 'Clarification'), ('other', 'Other')], default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='interactionrecord',
            name='client_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interactionrecord',
            name='internal_management_ticket_status',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('case_closed', 'Case Closed'), ('dispute_on_progress', 'Dispute on progress'), ('resolution_given', 'Resolution given'), ('others', 'Others')], default='na', max_length=100),
        ),
        migrations.AddField(
            model_name='interactionrecord',
            name='other_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interactionrecord',
            name='other_ticket_status',
            field=models.TextField(blank=True),
        ),
    ]
