# Generated by Django 3.2.5 on 2021-08-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0015_auto_20210806_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionrecord',
            name='dispute_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interactionrecord',
            name='memo_solution_from_the_mgmt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interactionrecord',
            name='client_feedback_status',
            field=models.CharField(blank=True, choices=[('dispute', 'Dispute'), ('n/a', 'N/A'), ('clarification', 'Clarification'), ('case_closed', 'Case Closed'), ('dispute_on_progress', 'Dispute on progress'), ('resolution_given', 'Resolution given'), ('other', 'Other')], default='n/a', max_length=100),
        ),
    ]
