# Generated by Django 3.2.5 on 2021-08-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_client_hourly_rate_currency'),
        ('post_paid', '0016_auto_20210809_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteractionpostpaid',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_paid_customer_interaction_agents', to='authentication.staff'),
        ),
    ]
