# Generated by Django 3.2.5 on 2021-08-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0017_customerinteractionpostpaid_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestedtobuy',
            options={'verbose_name': 'Interested to Buy', 'verbose_name_plural': 'Interested to Buy'},
        ),
        migrations.AlterModelOptions(
            name='interestedtosell',
            options={'verbose_name': 'Interested to Sell', 'verbose_name_plural': 'Interested to Sell'},
        ),
    ]
