# Generated by Django 3.2.5 on 2021-08-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0018_auto_20210812_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAuditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerinteractionpostpaid',
            name='internal_auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_paid_customer_interaction_auditors', to='post_paid.internalauditor'),
        ),
    ]
