# Generated by Django 3.2.5 on 2021-08-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0020_remove_customerinteractionpostpaid_script_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderpostpaid',
            name='total_time_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
