# Generated by Django 3.2.5 on 2021-08-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0023_alter_joborderpostpaid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutesreport',
            name='monthly_usage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='minutesreport',
            name='total_minutes_unused',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
