# Generated by Django 3.2.5 on 2021-08-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0024_auto_20210817_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutesreport',
            options={'verbose_name': 'Month to Month Usage Overview', 'verbose_name_plural': 'Month to Month Usage Overview'},
        ),
        migrations.AlterModelOptions(
            name='monthlycharge',
            options={'ordering': ['-client'], 'verbose_name': 'Plan Summary and Payment', 'verbose_name_plural': 'Plan Summary and Payments'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-company'], 'verbose_name': 'Customer Registration Info', 'verbose_name_plural': 'Customer Registration Info'},
        ),
    ]
