# Generated by Django 3.2.5 on 2021-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0025_auto_20210817_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobordercomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='monthlycharge',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
