# Generated by Django 3.2.5 on 2021-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0026_auto_20210818_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutesreport',
            name='ci_minutes_overview',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='minutesreport',
            name='general_request_total_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
