# Generated by Django 3.2.5 on 2021-08-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0028_auto_20210824_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinteractionpostpaid',
            options={'ordering': ['-ticket_number'], 'verbose_name': 'Postpaid Customer Interaction Board', 'verbose_name_plural': 'Postpaid Customer Interaction Board'},
        ),
        migrations.AlterField(
            model_name='interactionrecord',
            name='total_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19, null=True),
        ),
    ]
