# Generated by Django 3.2.7 on 2021-09-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0029_auto_20210831_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='billing_status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
