# Generated by Django 3.2.8 on 2023-04-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("callme", "0026_form_customer_interaction_prepaid"),
        ("authentication", "0005_alter_client_hourly_rate_currency"),
        ("post_paid", "0031_auto_20230424_1940"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.CharField(blank=True, max_length=250)),
                ("apn", models.CharField(blank=True, max_length=250)),
                ("reference_number", models.CharField(blank=True, max_length=250)),
                ("county", models.CharField(blank=True, max_length=250)),
                ("state", models.CharField(blank=True, max_length=250)),
                ("address", models.TextField(blank=True)),
                ("caller_full_name", models.CharField(blank=True, max_length=250)),
                ("caller_phone", models.CharField(blank=True, max_length=250)),
                ("email", models.CharField(blank=True, max_length=250)),
                ("reason_of_the_call", models.TextField(blank=True)),
                (
                    "crm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "yes"),
                            ("no", "No"),
                            ("needs_validation", "Needs validation"),
                            ("invalid_data", "Invalid data"),
                            ("needs_follow_up", "Needs follow-up"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "leads_transferred_crm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("needs_transferred", "Needs transferred"),
                            ("transfer_complete", "Transfer complete"),
                            ("na", "N/A"),
                        ],
                        max_length=250,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acquisition_tagging",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_summary_acquisitions",
                        to="post_paid.acquisition",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_summary_agents",
                        to="authentication.staff",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ticket_summary_company",
                        to="callme.company",
                    ),
                ),
                (
                    "disposition_tagging",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_summary_dispotions",
                        to="post_paid.acquisition",
                    ),
                ),
                (
                    "general_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_summary_general_call",
                        to="post_paid.generalcall",
                    ),
                ),
                (
                    "interested_to_buy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_summary_interested_to_buy",
                        to="post_paid.interestedtobuy",
                    ),
                ),
                (
                    "interested_to_sell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_summary_interested_to_sell",
                        to="post_paid.interestedtosell",
                    ),
                ),
                (
                    "internal_auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_summary_internal_auditors",
                        to="post_paid.internalauditor",
                    ),
                ),
                (
                    "prep_for_marketing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_summary_pre_for_marketings",
                        to="post_paid.acquisition",
                    ),
                ),
                (
                    "sales_team_assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_summary_sales_team",
                        to="authentication.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Summary",
                "verbose_name_plural": "Ticket Summaries",
            },
        ),
    ]
