# Generated by Django 3.2.8 on 2023-05-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post_paid", "0033_disposition_prepformarketing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketsummary",
            name="disposition_tagging",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket_summary_dispotions",
                to="post_paid.disposition",
            ),
        ),
        migrations.AlterField(
            model_name="ticketsummary",
            name="prep_for_marketing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket_summary_pre_for_marketings",
                to="post_paid.prepformarketing",
            ),
        ),
    ]
