# Generated by Django 3.2.8 on 2023-05-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post_paid", "0035_overalltagging"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketsummary",
            name="overall_tagging",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket_summary_overall_taggings",
                to="post_paid.overalltagging",
            ),
        ),
    ]
