# Generated by Django 3.2.8 on 2023-05-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_user_sub_category"),
        ("post_paid", "0037_ticketsummarycomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSummaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_called", models.DateField(auto_now_add=True)),
                ("ticket_number", models.CharField(blank=True, max_length=250)),
                (
                    "total_minutes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=19,
                        null=True,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("submitted", "Submitted"), ("approved", "Approved")],
                        default="approved",
                        max_length=50,
                    ),
                ),
                (
                    "client_feedback_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dispute", "Dispute"),
                            ("n/a", "N/A"),
                            ("clarification", "Clarification"),
                            ("case_closed", "Case Closed"),
                            ("dispute_on_progress", "Dispute on progress"),
                            ("resolution_given", "Resolution given"),
                            ("other", "Other"),
                        ],
                        default="n/a",
                        max_length=100,
                    ),
                ),
                ("dispute_details", models.TextField(blank=True)),
                ("other_feedback", models.TextField(blank=True)),
                ("client_notes", models.TextField(blank=True)),
                (
                    "internal_management_ticket_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("na", "N/A"),
                            ("case_closed", "Case Closed"),
                            ("dispute_on_progress", "Dispute on progress"),
                            ("resolution_given", "Resolution given"),
                            ("others", "Others"),
                        ],
                        default="na",
                        max_length=100,
                    ),
                ),
                ("memo_solution_from_the_mgmt", models.TextField(blank=True)),
                ("other_ticket_status", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_ticket_summary_records",
                        to="authentication.staff",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_ticket_summary_records",
                        to="authentication.client",
                    ),
                ),
                (
                    "ticket_summary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_summary_records",
                        to="post_paid.ticketsummary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Summary Record Breakdown",
                "verbose_name_plural": "Ticket Summary Record Breakdown",
                "ordering": ["-client"],
            },
        ),
    ]
