# Generated by Django 3.2.4 on 2021-06-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attributetype',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
