# Generated by Django 3.2.3 on 2021-05-31 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonesystem',
            name='client',
        ),
    ]
