# Generated by Django 3.2.4 on 2021-06-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0003_script_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('question', 'Question')], max_length=20)),
                ('value_text', models.CharField(blank=True, max_length=500)),
                ('value_question', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='form',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='form',
            name='value_question',
        ),
        migrations.RemoveField(
            model_name='form',
            name='value_text',
        ),
        migrations.AddField(
            model_name='form',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_forms', to='callme.company'),
        ),
        migrations.DeleteModel(
            name='AttributeType',
        ),
        migrations.AddField(
            model_name='attribute',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_forms', to='callme.form'),
        ),
    ]
