# Generated by Django 3.2.4 on 2021-06-12 05:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0004_auto_20210612_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='mailing_lists',
            field=django_mysql.models.ListTextField(models.CharField(max_length=500), size=100),
        ),
    ]
