# Generated by Django 3.2.4 on 2021-06-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0005_alter_script_mailing_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_forms', to='callme.form'),
        ),
    ]
