# Generated by Django 3.2.4 on 2021-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0006_alter_attribute_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('llcs', 'LLCs'), ('others', 'Others')], max_length=250),
        ),
    ]
