# Generated by Django 3.2.4 on 2021-06-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0007_alter_company_business_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-client'], 'verbose_name': 'List of Company', 'verbose_name_plural': 'List of Companies'},
        ),
        migrations.AlterModelOptions(
            name='phonesystem',
            options={'ordering': ['-company'], 'verbose_name': 'Sub Number Phone Set up'},
        ),
    ]
