# Generated by Django 3.2.4 on 2021-06-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_paid', '0007_auto_20210628_0235'),
        ('callme', '0010_county_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='customer_interaction_post_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_interaction_post_paid_forms', to='post_paid.customerinteractionpostpaid'),
        ),
    ]
