# Generated by Django 3.2.4 on 2021-06-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0011_form_customer_interaction_post_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='original_script',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
