# Generated by Django 3.2.4 on 2021-06-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0012_form_original_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apn', models.CharField(max_length=500)),
                ('reference', models.CharField(max_length=500)),
                ('property_size', models.CharField(max_length=250)),
                ('short_legal_description', models.TextField()),
                ('property_address', models.TextField()),
                ('property_city', models.TextField()),
                ('property_county', models.CharField(max_length=250)),
                ('property_state', models.CharField(max_length=250)),
                ('property_zip', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('approved_option_amount', models.TextField()),
                ('other_terms', models.TextField()),
                ('offer_amount', models.TextField()),
                ('other_offer_terms', models.TextField()),
                ('notes', models.TextField()),
                ('offer_status_notes', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_customer_infos', to='callme.company')),
                ('offer_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_info_status', to='callme.offerstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
