# Generated by Django 3.2.4 on 2021-07-01 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0013_customerinfo_offerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='apn',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='approved_option_amount',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='offer_amount',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='offer_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_info_status', to='callme.offerstatus'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='offer_status_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='other_offer_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='other_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='property_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='property_city',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='property_county',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='property_size',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='property_state',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='property_zip',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='reference',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='short_legal_description',
            field=models.TextField(blank=True),
        ),
    ]
