# Generated by Django 3.2.4 on 2021-07-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0014_auto_20210701_0515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerInfo',
            new_name='CallMeInfo',
        ),
    ]
