# Generated by Django 3.2.4 on 2021-07-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0015_rename_customerinfo_callmeinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callmeinfo',
            old_name='offer_amount',
            new_name='buyer_offer_amount',
        ),
        migrations.AddField(
            model_name='callmeinfo',
            name='seller_offer_amount',
            field=models.TextField(blank=True),
        ),
    ]
