# Generated by Django 3.2.4 on 2021-07-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0016_auto_20210705_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callmeinfo',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='callmeinfo',
            name='last_name',
        ),
    ]
