# Generated by Django 3.2.4 on 2021-07-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0017_auto_20210706_0730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallMeInfo',
            new_name='PropertyInfo',
        ),
    ]
