# Generated by Django 3.2.5 on 2021-07-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0018_rename_callmeinfo_propertyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
