# Generated by Django 3.2.5 on 2021-07-23 07:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0019_propertyfileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='mailing_lists',
            field=django_mysql.models.ListTextField(models.CharField(max_length=500), blank=True, null=True, size=100),
        ),
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
