# Generated by Django 3.2.5 on 2021-07-23 08:36

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0020_auto_20210723_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value_question',
            field=django_bleach.models.BleachField(blank=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_text',
            field=django_bleach.models.BleachField(blank=True),
        ),
    ]
