# Generated by Django 3.2.5 on 2021-08-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0022_auto_20210728_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm',
            name='crm_login',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='crm',
            name='crm_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='crm',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='crm',
            name='type_of_crm',
            field=models.TextField(blank=True),
        ),
    ]
