# Generated by Django 3.2.5 on 2021-08-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0023_auto_20210804_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonesystem',
            options={'ordering': ['-company'], 'verbose_name': 'List of Sub Numbers', 'verbose_name_plural': 'List of Sub Numbers'},
        ),
        migrations.AlterField(
            model_name='crm',
            name='crm_login',
            field=models.TextField(blank=True),
        ),
    ]
