# Generated by Django 3.2.5 on 2021-08-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0024_auto_20210812_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='mailing_lists_unpacked',
            field=models.TextField(blank=True),
        ),
    ]
