# Generated by Django 3.2.7 on 2021-09-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepaid', '0005_prepaid_subscriptiontype'),
        ('callme', '0025_form_mailing_lists_unpacked'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='customer_interaction_prepaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_interaction_prepaid_forms', to='prepaid.customerinteractionprepaid'),
        ),
    ]
