# Generated by Django 3.2.8 on 2023-05-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callme", "0026_form_customer_interaction_prepaid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="form_title",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
