# Generated by Django 3.2.8 on 2023-05-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post_paid", "0039_joborderticketsummary_joborderticketsummarycomment"),
        ("callme", "0027_alter_form_form_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="ticket_summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket_summary_forms",
                to="post_paid.ticketsummary",
            ),
        ),
    ]
