# Generated by Django 3.2.8 on 2023-06-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callme", "0028_form_ticket_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_code", models.CharField(blank=True, max_length=250)),
                ("full_name", models.CharField(blank=True, max_length=250)),
                ("company_name", models.CharField(blank=True, max_length=250)),
                ("reference_number", models.CharField(blank=True, max_length=250)),
                ("apn", models.CharField(blank=True, max_length=250)),
                ("county", models.CharField(blank=True, max_length=250)),
                ("state", models.CharField(blank=True, max_length=250)),
                ("size", models.CharField(blank=True, max_length=250)),
                ("address", models.CharField(blank=True, max_length=250)),
                ("price", models.CharField(blank=True, max_length=250)),
                ("due_diligence", models.TextField(blank=True)),
                ("ad_content", models.TextField(blank=True)),
                ("images", models.TextField(blank=True)),
                ("website", models.TextField(blank=True)),
                ("comment_offer_tab_customer", models.TextField(blank=True)),
                ("comment_offer_tab_client", models.TextField(blank=True)),
                ("comment_sales_agent_notes", models.TextField(blank=True)),
                ("facebook", models.CharField(blank=True, max_length=250)),
                ("fb_groups", models.CharField(blank=True, max_length=250)),
                ("landmodo", models.CharField(blank=True, max_length=250)),
                ("fsbo", models.CharField(blank=True, max_length=250)),
                ("instagram", models.CharField(blank=True, max_length=250)),
                ("land_listing", models.CharField(blank=True, max_length=250)),
                ("land_flip", models.CharField(blank=True, max_length=250)),
                ("land_hub", models.CharField(blank=True, max_length=250)),
                ("land_century", models.CharField(blank=True, max_length=250)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
