# Generated by Django 3.2.8 on 2023-06-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("callme", "0029_property"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="approved_option_amount",
            new_name="ad_content",
        ),
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="property_county",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="property_size",
            new_name="client_code",
        ),
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="buyer_offer_amount",
            new_name="comment_offer_tab_client",
        ),
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="notes",
            new_name="comment_offer_tab_customer",
        ),
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="offer_status_notes",
            new_name="comment_sales_agent_notes",
        ),
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="property_state",
            new_name="county",
        ),
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="other_offer_terms",
            new_name="due_diligence",
        ),
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="property_zip",
            new_name="facebook",
        ),
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="other_terms",
            new_name="images",
        ),
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="property_address",
            new_name="website",
        ),
        migrations.RemoveField(
            model_name="propertyinfo",
            name="company",
        ),
        migrations.RemoveField(
            model_name="propertyinfo",
            name="offer_status",
        ),
        migrations.RemoveField(
            model_name="propertyinfo",
            name="property_city",
        ),
        migrations.RemoveField(
            model_name="propertyinfo",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="propertyinfo",
            name="seller_offer_amount",
        ),
        migrations.RemoveField(
            model_name="propertyinfo",
            name="short_legal_description",
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="fb_groups",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="fsbo",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="instagram",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="land_century",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="land_flip",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="land_hub",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="land_listing",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="landmodo",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="price",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="reference_number",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="size",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="propertyinfo",
            name="state",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="propertyinfo",
            name="apn",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
