# Generated by Django 3.2.8 on 2023-06-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0030_auto_20230609_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
