# Generated by Django 3.2.8 on 2023-06-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0032_commentoffertabagent_commentoffertabclient_commentoffertabcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentoffertabagent',
            name='property_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_info_comment_tab_agent', to='callme.propertyinfo'),
        ),
        migrations.AddField(
            model_name='commentoffertabclient',
            name='property_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_info_comment_tab_client', to='callme.propertyinfo'),
        ),
        migrations.AddField(
            model_name='commentoffertabcustomer',
            name='property_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_info_comment_tab_customers', to='callme.propertyinfo'),
        ),
    ]
