# Generated by Django 3.2.8 on 2023-06-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callme', '0033_auto_20230617_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentoffertabagent',
            name='property_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_info_comment_tab_agents', to='callme.propertyinfo'),
        ),
        migrations.AlterField(
            model_name='commentoffertabclient',
            name='property_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_info_comment_tab_clients', to='callme.propertyinfo'),
        ),
    ]
