# Generated by Django 3.2.3 on 2021-05-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=40),
        ),
    ]
