# Generated by Django 3.2.8 on 2023-01-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_client_hourly_rate_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation_category',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('new_client', 'New Client'), ('current_client', 'Current Client'), ('affiliate_partner', 'Affiliate Partner'), ('inactive_client', 'Inactive Client')], max_length=30),
        ),
    ]
