# Generated by Django 3.2.8 on 2022-01-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_client_hourly_rate_currency'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('closed', 'Closed'), ('resolution_provided', 'Resolution provided')], default='pending', max_length=250)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.staff')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resolutioncategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
            options={
                'verbose_name': 'Resolution',
                'verbose_name_plural': 'Resolutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolution.resolution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
