# Generated by Django 3.2.8 on 2022-01-27 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resolution', '0002_auto_20220125_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resolution_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
